FROM wordpress:php8.0-apache

# Optional: copy custom wp-config or plugins
# COPY 192.129.0.1 /var/www/html/192.129.0.1

# ensure correct permissions
RUN chown -R www-data:www-data /var/www/html

EXPOSE 80
