apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: {{ include "wordpress.fullname" . }}-mysql
  clusterIP: None
