apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}-wordpress
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "wordpress.fullname" . }}-wordpress
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
